name: anaconda-client-env
channels:
  - conda-forge
  - defaults
dependencies:
  - anaconda-client
  - pip
  - python
  - geopandas
  - h5py
  - netcdf4
  - scipy
  - matplotlib
  - scikit-learn
  - basemap
  - pyhdf
  - lunardate
  - lunarcalendar
 
